### ISSUE TITLE
`clear()` isn't called on expired events in `EventIntake`

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#10198]
From `EventIntake::addEvent`:

```
            // an expired event will cause ShadowGraph to throw an exception, so we just to discard it
            if (consensus().isExpired(event)) {
                return;
            }
```

Expired `EventImpl`s are discarded, without `clear()` first being called

**Comment by lpetrovic05** [comment]
I don't think its a realistic issue because an expired event will probably not be linked to any other events, so there is nothing to clear. Even if it is linked, there will be nothing linking to it, so it still could be garbage collected. But its always a good idea to be on the safe side and clear it just in case.
