### ISSUE TITLE
Use the correct PRNG contract address in child records

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#10552]
When we call a PrngContract, we save the record with the HTC contract address. This is done in mod so we can mirror mono, but we should fix it after the differential testing.

Full context: https://github.com/hashgraph/hedera-services/pull/10074#discussion_r1409208043

**Comment by bibitibooo1** [comment]
The problem was that the Prng contract was using HTS contract address. We implemented it like this in mod as well so we can match mono. You can see the usage of SystemContractUtils.HTS_PRECOMPILE_MIRROR_ID and you can see it's used in PrngSystemContract - we should fix this. 

Currently, it's used in createFailedRecord but we think that is was used in some other places as well and maybe got fixed there? We should check. Nonetheless we should fix PrngSystemContract.createFailedRecord to use the Prng contract address instead of the HTS.
