### ISSUE TITLE
Add support for automatic Maven Central releases

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-services#11237]
## Description

We need to add support to automatically release the existing artifacts published to Maven Central currently. Additionally, we want to enable publishing of the remaining `hedera-*` artifacts with the exception of `hedera-mono-service` and `test-clients`. No changes required to the `com.swirlds` artifacts which are being published except to automatically release them. The new `block-node` folder and it's projects should be published and automatically released as well.

**Comment by jjohannes** [comment]
[This PR](https://github.com/hashgraph/hedera-services/pull/11731) addresses both topics **automated publishing** and **publish all components from services and blocknode**.

Contrary to the issue description, I think `hedera-mono-services` needs to be published as well, because other published components depend on it.

Not published services projects are: `cli-clients` and `test-clients`

I had to made a few other decisions were we still might need to adjust something. See comments on: https://github.com/hashgraph/hedera-services/pull/11731
