### ISSUE TITLE
Test failed due to exception from AbstractMetricAdapter

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#11305]
### Description

All service tests failed due to exception from swirdsl.log:

```
2024-02-01 06:58:09.205 92       ERROR EXCEPTION        <<platform-core: MetricsThread #0>> AbstractMetricAdapter: name field changed for metric:DefaultSpeedometerMetric[category=app,name=systemDeleteRcv/sec,description=number of systemDelete received per second,unit=,format=%,13.2f,dataType=FLOAT,halfLife=10.0,value=0.0] from:systemDeleteRcv/sec to:systemDeleteRcv_per_sec
```

### Steps to reproduce

All nightly test panels

### Hedera network

other

### Version

latest

### Operating system

Linux

**Comment by mxtartaglia-sl** [comment]
@JeffreyDallas 
This is an expected exception. Newer metrics should comply with the naming rules defined.

We use Prometheus as the underlying metric backend, which has some limitations in naming the metrics. We should avoid charters like '.' '-' ' ' "/" and "%".
Our framework caught metric names that contained such characters and changed them under the hood for others, creating a discrepancy between the metric name in the code and what we see in the dashboard.
To reduce this situation and remove the possibility of being unable to check a metric because of bad naming, there is now a validation performed that is meant to fail JRS test when a new metric contains such characters. The framework still corrects them, so there is no danger of creating a production issue, but if you see a test failing because of this, you should rename the metric in the code to comply with the rule.
Rules:
replace '.' for ':'
replace '-' for '_'
replace ' ' for '_'
replace "/" for "_per_"
replace "%" for "Percent"
Use only Latin letters or numbers. 
The solution is to change the offending metric name to one complying with the rules, in this case, stemDeleteRcv_per_sec, 
but if you have a particular branch that is failing, I can talk to the dev to fix the issue because I am not seeing that particular metric in hedera-services develop branch

**Comment by mxtartaglia-sl** [comment]
Providing an update: although the previous comment is correct, application metrics should have been incorporated into the original metric name change. 
@JeffreyDallas provided me with the link to failing tests and I am addressing the changes.
