### ISSUE TITLE
Signatures on a scheduled txn must not be reusable in a replay ScheduleCreate

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1155]
**Summary of the defect**
- Alice uses a `ScheduleCreate` to schedule a `SubmitMessage` txn `X`, and then Bob signs `X` with the topic's submit key in a `ScheduleSign`.
- The record stream now contains Bob's submit key signature `S` on `X`.
- Carol can replay `X` by doing a `ScheduleCreate` with `X` as the inner txn, herself as the payer, and an inner `sigMap` that includes `S` and her signature on `X`.

**Suggested fix**
1. Require the inner txn in a `ScheduleCreate` to have the same `TransactionID.transactionValidStart` as the outer txn. 
**_Purpose:_** prevent re-scheduling a txn more than 3 minutes after it was first scheduled.
2. When creating the content-addressable key used to merge idempotent `ScheduleCreate`'s, do not directly use the submitted inner `transactionBody`; instead use a deserialized `TransactionBody` object with the valid start cleared. 
**_Purpose:_** continue to support idempotent creation.
3. After a scheduled txn has executed, keep its `MerkleSchedule` in state until it expires; reject any new `ScheduleCreate` whose content-addressable key collides with the executed txn.
**_Purpose:_** prevent re-scheduling a txn within 3 minutes after it was first scheduled and executed.

**Comment by lbaird** [comment]
There is a possible alternative that might have some advantages:


  1.   Require that the valid start time of the inner transaction matches the expiration time for the created scheduled transaction entity.
  2.  Continue to deduplicate using the byte array (protobuf binary of the inner transaction), rather than trying to match deserialized info.
  3.  Keep an entity in memory until its expiration date. But mark it as deleted after it executes. It can also then be reduced to just a hash of the inner transaction plus expiration date.

This approach allows us to continue deduplicating based on the raw byte array, rather than trying to deserialize and trying to match up the deserialized data. It especially avoids problems where the software is updated with a new deserialization format between the time the scheduled transaction entity is created and when it executes. It’s better to deduplicate on the simplest possible thing: the hash of the binary byte array.

It’s true that the entity will need to exist in state until its expiration date (which is also stored inside the inner transaction as its “valid start time”). But after executing, the entity can be shrunk to only a small number of bytes: the expiration date and the hash of the byte array. That’s just for deduping. Similarly, if the admin deletes it, it should remain there, marked as deleted, until it expires.

For now, expiration will always be 30 minutes after the outer travesction’s vslud start time.

________________________________

**Comment by tinker-michaelj** [comment]
@lbaird If the inner txn's `validStart` is determined by the outer txn's `validStart`, but we deduplicate by the submitted byte array, then doesn't this break our current use of idempotent scheduling?

I.e. all the scheduling accounts must agree out-of-band on the `validStart` they will use, right?

**Comment by lbaird** [comment]
I suggested that the inner validStart match the outer expiration date, not the outer validStart. So it would be idempotent, assuming everyone chose the same expiration time.

And that makes sense: if two transactions are scheduled to happen at different times, then they really are different transactions. But if they’re set to happen at the same time, and are byte-for-byte identical, then they’re the same transaction.

At the moment, we aren’t allowing scheduled transactions to pick arbitrary expiration times, but are forcing them to expire 30 minutes after the outer validStart. So it would be necessary for users to submit with the same outer valid start. That requirement will go away as soon as we relax the 30-minute requirement.

________________________________

**Comment by tinker-michaelj** [comment]
> I suggested that the inner validStart match the outer expiration date, not the outer validStart. So it would be idempotent, assuming everyone chose the same expiration time.

@lbaird The LimeChain bridge relies on the Validator nodes being able to each use their own `validStart`; that's why I added the extra step of using content-addressable keys that ignore the inner txn's `validStart`.

Would prefer us to require a bit extra coordination amongst clients? (This will certainly reduce the work the nodes have to do!)

**Comment by bugbytesinc** [comment]
Having a schedule create body contain another transaction body seems to be more complex than it could be.

Why not a more simple API surface, say let the presence of `transactionValidDuration` indicate that 
this could be a partial signature (in practice, this value is not valuable given the maximum that can
be specified is 3 minutes) and returning a status of "PENDING_SIGNATURES" if the node does not receive
all necessary signatures instead of `SUCESS`.  Therefore your Transaction ID will be unique from the 
start based on previous convention.  The remainder of he API can reamin similar to what you have now, you
still have to pass around the bodybytes of the transaction, but now it carries a easy to track transaction id.

(overlooking the admin key for sake of argument, but finding a place for it should be easy)

**Comment by tinker-michaelj** [comment]
@bugbytesinc Very cool idea! ❤️  Interested to see what others think.
