### ISSUE TITLE
Investigate code coverage discrepancies between Codacy, JaCoCo, and CodeCov

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-services#11565]
## Description

The code coverage numbers reported by Codacy, CodeCov, and JaCoCo appear to all report different coverage figures which possibly indicates one or more configuration issues.

Additionally, there is a concern some code coverage is not being properly picked up or reported at all.

**Comment by jjohannes** [comment]
State after some investigation:
- `Codecov` upload broken right now `Error: Codecov token not found.`
- Both 'Codecov' and 'Codacy' use the JaCoCo XML reports as base. These are right now created per-project. Which only gives a "partial view" on the overall coverage. Code that is covered by tests (e.g. in API only projects of _services_ like `hedera-smart-contract-service`) is counted as uncovered, because there are not tests directly **in the API project** covering them. I think it would be better to let Gradle aggregate a full report (one XML file) and then pass that to both 'Codecov' and 'Codacy'. Then we have the same input for both and can also generate a corresponding HTML report with JaCoCo/Gradle only locally. WiP PR: https://github.com/hashgraph/hedera-services/pull/13073

**Comment by jjohannes** [comment]
Waiting for this to be fixed:

```
gpg: key 806BB28AED779869: public key "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1

gpg: Signature made Thu Apr 18 16:30:38 2024 UTC
gpg:                using RSA key 27034E7FDB850E0BBC2C62FF806BB28AED779869
gpg: Good signature from "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
...
Warning: Codecov: Failed to properly create commit: The process '/runner/_work/_actions/codecov/codecov-action/54bcd8715eee62d40e33596ef5e8f0f48dbbccab/dist/codecov' failed with exit code 1
```

https://github.com/hashgraph/hedera-services/actions/runs/8923474325/job/24507810586#step:54:38

**Comment by jjohannes** [comment]
### Investigation results
- With #13073, we make sure the same data is uploaded to both both `Codecov` and `Codacy` (as a single aggregated XML file)
- With #13073, there is also an aggregated report to view locally after running `:reports:testCodeCoverageReport`
- The numbers in the reports are different because:
   - The **local report** takes generated code (protobuf and dagger) into account. Therfore it sees more sources and the _coverage percentage is lower_.
   - IIUC, `Codecov` and `Codacy` take the code directly from the Git repository. So they cannot see the generated code. As a result the _coverage percentage is higher_. I experimented with excluding generated classes from the report aggregation in general and then the number in the local report and Codecov align.
   - The number in `Codacy` is always slightly higher. I am not  totally sure why that is, but I assume the calculation, while based on the same data, works a bit different. What I suspect is that `Codecov` counts every line touched as "fully covered" (like [here](https://app.codacy.com/gh/hashgraph/hedera-services/coverage/files/114664308753?branch=11565-unify-code-coverage-setup) - 100% covered), while `Codacy` also takes "partial coverage" in case of "if-else" branching into account (liker [here](https://app.codecov.io/gh/hashgraph/hedera-services/blob/11565-unify-code-coverage-setup/hedera-node%2Fhapi-utils%2Fsrc%2Fmain%2Fjava%2Fcom%2Fhedera%2Fnode%2Fapp%2Fhapi%2Futils%2Fethereum%2FEthTxSigs.java) - same file, but 99.07% covered).
