### ISSUE TITLE
Kibana - Add visualizations for topic, token and scheduled requests

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1166]
Check if these visualizations exist and add if they don't for:
- [x] testnet
- [x] mainnet
- [x] performance net
- [x] performance net 2

This is to support the investigation of https://github.com/swirlds/swirlds-platform/issues/3075

**Comment by abhishek-hedera** [comment]
I created a dashboard with all visualizations for HSS on Testnet. To export it faster to other environments, I have exported only the dashboard and related objects to Perfnet and before importing I also checked the option to notify before overwriting. By only skipping the Filebeat* import, the new dashboard and its visualizations were imported successfully.

**Comment by abhishek-hedera** [comment]
For the Kibana visualizations on Performance Net 2, when importing the exports from Testnet it generates an error for all visualizations and dashboards that id fields are unrecognized for all visualizations. This happens because when I try to create a new visualization with a service field from either Schedule or Token, it doesn't populate in the list of available fields and hence it shows as unrecognized. This however is not the case when using Discover option as it shows all the fields from Schedule and Token.

**Comment by abhishek-hedera** [comment]
Mainnet uses Kibana version 6.8.9 and other pre-prod nets use Kibana verison 7.11. The import of dashboards and visualizations from newer version would not work with older versions. This could be resolved by either manually creating all visualizations and dashboards in Mainnet or upgrading the mainnet version to 7.11 for the import/export to work.
