### ISSUE TITLE
Document `XTest` concepts, best practices, and TODOs

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#11680]
### Problem

The `XTest` framework now has many examples (of varying clarity), but no documentation.

### Solution

Add a README clarifying what an `XTest` is, highlight the best examples, and list issues with the current state of affairs.

**Comment by david-bakin-sl** [comment]
As part of this documentation there should be a "philosophy" of XTest.  Here's my version of what we wanted to achieve when we started this initiative:

- Easier to write, read and understand, and to debug into than the HAPI suite BDDs because they just exercise the service (or services directly) through its API instead of being an end-to-end test where a HAPI transaction goes in and a record stream comes out, with all kinds of concurrency and asynchronicity happening in between, and the measurement of the effect being rather indirect. 
- At the same time making it easier to test edge cases because you can hand-craft test data using the actual data structures taken by the API, and can thus drive the system into states it can't normally get to by driving it with HAPI transactions.
- A more complete test of the service-under-test than (our current) unit tests because mocking is extremely discouraged.  So you're actually testing the real code instead of hard-wiring in to the test a bunch of assumptions of how the real code is supposed to work.

**Comment by lukelee-sl** [comment]
Adding on to the comments by @david-bakin-sl above, 
- xTests are ideally suited for testing and understanding inter module interactions such as dispatching transactions from smart contracts service to token service
- Executes more quickly and thus allows the developer to iterate between test and functionality more efficiently.

There are tests which xTests do not cater well to at present and these should be noted.  In particular,
- Any test that require multiple nodes to be running
- Tests that require complex signing/signature verification
- Any test where the existing scaffolding infrastructure needs to be significantly modified (although this will likely become more flexible over time)
