### ISSUE TITLE
JMH IntelliJ integration

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#11863]
IntelliJ has a play button for JMH tests:
<img width="421" alt="image" src="https://github.com/hashgraph/hedera-services/assets/20076809/b89aea19-7ee2-4154-bc4a-46ea75b379fc">

Unfortunately, when trying to run a JMH test this way, it will not run. This would be a useful feature to have.

**Comment by hendrikebbers** [comment]
Or at least have a pattern for a command line call to execute only 1 JMH test

**Comment by jjohannes** [comment]
The example in the description can be confusing. The button is there, because there is a `main(...)` method in `ConsensusBenchmark` so IntelliJ offers to run it as a Java application. If you look at other tests – for example `LoggingBenchmark` – there is no button.

----

Is there any good way to run a single test right now with a Gradle command? As far as I can see, the Gradle plugin does not offer something for that out of the box. I could add a parameter so that you can do:

`./gradlew :swirlds-logging:jmh -PjmhTests=LoggingBenchmark$executeSimpleLogWithMessageWithPlaceholder`

Would that make sense?

Then there is an IntelliJ plugin: https://plugins.jetbrains.com/plugin/7529-jmh-java-microbenchmark-harness
I tried this, with one modification to the setup it seems to work well:

![bench](https://github.com/hashgraph/hedera-services/assets/1963746/b43da4f1-96b4-468a-83f5-0f29a7db064d)


I can prepare a PR to:
1) ...allow running a single test from command line using `-PjmhTests`
2) ...using the IntelliJ plugin to run from IntelliJ

**Comment by jjohannes** [comment]
Please install the plugin and give this a try: https://github.com/hashgraph/hedera-services/pull/11865
