### ISSUE TITLE
Queries charge wrong fee

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#12592]
The following queries charge too much fee:

- [x] AccountInfoQuery
- [x] AccountRecordsQuery
- [x] ContractCallQuery
- [x] ContractInfoQuery
- [x]  ContractByteCodeQuery
- [x] FileContentsQuery
- [x] FileInfoQuery
- [x] NetworkVersionInfoQuery
- [x] ScheduleInfoQuery
- [x] TokenInfoQuery
- [x] TokenNftInfoQuery
- [x]  TopicInfoQuery
- [x] TransactionRecordQuery

**Comment by Neeharika-Sompalli** [comment]
Based on the reproduction steps provided [here](https://github.com/hashgraph/hedera-sdk-java/pull/1764/files)  in `TempExample` the way we are computing the cost is wrong. 

The query cost is node payment + the amount needed to pay for cryptoTransfer to send the node payment.
Since it is just checking balance difference, it includes cryptoTransfer cost.

The only Query that seems wrong is `CopntractCallLocal`
