### ISSUE TITLE
Stabilize HAPI Test (Restart)

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#13032]
The HAPI Test (Restart) is flaky and must be stabilized before we can make it a required check.

An example is this [test run](https://github.com/hashgraph/hedera-services/actions/runs/8863075592/job/24336788626?pr=13031).

Interestingly, the first error message in the log is the one below. Maybe it is an infrastructure issue and not the test itself that is flaky.
```
2024-04-28 03:55:13.816 ERROR 107  ReadableFreezeUpgradeActions - Failed to write NMT marker /opt/hgcapp/services-hedera/HapiApp2.0/data/upgrade/current/now_frozen.mf
java.nio.file.AccessDeniedException: /opt/hgcapp
```

**Comment by Neeharika-Sompalli** [comment]
Seems like this is not very reproducible and @nathanklick was suspecting this could be a race condition, because all nodes are writing to the same place in `/opt/hgcapp/`. This could be a problem we have not thought about running multiple nodes in CI. 

Will spend more time on this, if this error is reproducible in many PRs.
