### ISSUE TITLE
Failed to hash virtual map after reconnect

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#13064]
Example failing test: http://35.247.76.217:8095/swirlds-automation/release/0.49/4N/Reconnect/20240430-094150-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/swirlds-logs.html

I've observed the following pattern of failure on mutliple tests in both `develop` and `release/0.49`.

- node falls behind (intentional node death)
- node attempts to reconnect
- reconnect fails because we fail to hash a virtual map

```
VirtualHasher: 	Failed to wait for all hashing tasks
		java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: hash
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653) ~[?:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hash(VirtualHasher.java:502) ~[swirlds-virtualmap-0.49.0.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.lambda$prepareReconnectHashing$4(VirtualRootNode.java:1483) ~[swirlds-virtualmap-0.49.0.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: hash
	at com.swirlds.common.crypto.HashBuilder.update(HashBuilder.java:169) ~[swirlds-common-0.49.0.jar:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher$ChunkHashTask.hash(VirtualHasher.java:263) ~[swirlds-virtualmap-0.49.0.jar:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher$ChunkHashTask.exec(VirtualHasher.java:236) ~[swirlds-virtualmap-0.49.0.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

**Comment by anthony-swirldslabs** [comment]
I don't have a deep expertise in this particular code. However, I've checked commits in 0.49 branch that were submitted since last week, and there doesn't seem to be a single one that could possibly affect this particular code. So I don't believe this is caused by a recent code change.

However, upon looking into the logs, just above the log quoted above, I see:

```
node3 | 26m 40.811s | WARN | AsyncOutputStream: | AsyncOutputStream interrupted
-- | -- | -- | -- | --
  | node3 | 26m 40.812s | ERROR | VirtualHasher: | Failed to wait for all hashing tasks
  |   | java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: hash

```

And further above, I see:

```

node0 | 26m 40.740s | WARN | NetworkUtils: | Connection broken: 0 -> 3 Caused by exception: MerkleSynchronizationException Message: Synchronization failed with exceptions Caused by exception: ExecutionException Message: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.internal.QueryResponse) Caused by exception: MerkleSynchronizationException Message: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.internal.QueryResponse) Caused by exception: SocketTimeoutException Message: Read timed out
-- | -- | -- | -- | --

```

And also:

```
node3 | 26m 40.793s | ERROR | StandardWorkGroup: | Work Group Exception [ groupName = learning-synchronizer ]
-- | -- | -- | -- | --
  |   | java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID -7441057967105127907(0x98BC0D340D9BCA1D) (class com.swirlds.common.merkle.synchronization.internal.Lesson)

```

The above logs lead me to believe that the failure is caused by a network connection failure, rather than by a problem in our code.

**Comment by artemananiev** [comment]
This failure looks very similar to what is described in https://github.com/hashgraph/hedera-services/issues/12046.

Some more info:

* The failure happened during reconnect, node 3 being a learner, node 0 being a teacher

* In teacher (node 0) logs: at `10:26:35` the teacher finished sending virtual map [0-8-1] (smartContracts) and started sending [0-9-1] (smartContractByteCode):

```
2024-04-30 10:26:35.541 21073    INFO  RECONNECT        <<platform-core: SyncProtocolWith3 0 to 3>> TeachingSynchronizer: finished sending tree
2024-04-30 10:26:35.759 21076    INFO  RECONNECT        <<platform-core: SyncProtocolWith3 0 to 3>> TeachingSynchronizer: sending tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 9 -> 1]
```

* On the learner side (node 3), virtual map [0-8-1] synchronization started at `10:23:16` (same time as it was started on the teacher) and took 7.5 minutes:

```
2024-04-30 10:23:16.635 7541     INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 8 -> 1]
2024-04-30 10:31:50.037 7618     INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 9 -> 1]
```

* By the time when the learner started receiving [0-9-1], `10:31:50`, the teacher had been already waiting for the first response from the learner for [0-9-1] for _more than 5 minutes_, it started at `10:26:35`. It caused the teacher to time out, since default config is to wait for 5 minutes, and eventually to close the connection

* Since the connection was closed, the very first read from the socket on the learner side failed with "Connection reset" exception. Due to far from ideal exception propagation code, it resulted in an NPE in hashing code, but this is not the root cause

**Comment by anthony-swirldslabs** [comment]
@cody-littley : if, as @artemananiev says, this issue is similar to #12046 , then we've added extra logs that could help shed some light on what's going on. However, these logs are only available in `develop`. Could you please share links to logs for the run with `develop` where this same test failed too?

**Comment by anthony-swirldslabs** [comment]
@cody-littley provided two additional links:

http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20240501-053547-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

A test fails with the same exception and the extra debug logs seem to be there.

http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20240429-053658-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

May or may not be helpful as well, but worth exploring.

**Comment by anthony-swirldslabs** [comment]
It looks like it took about 10 minutes for the learner to receive the tree `0 -> 8 -> 1`, and it failed about 1 second after it immediately started receiving the tree `0 -> 9 -> 1`:

```
node3 | 18m 5.787s | 2024-05-01 06:17:37.677 | INFO | LearningSynchronizer: | receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 8 -> 1]


node3 | 27m 51.251s | 2024-05-01 06:27:23.141 | INFO | LearningSynchronizer: | received tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 8 -> 1]
-- | -- | -- | -- | -- | --
node3 | 27m 51.251s | 2024-05-01 06:27:23.141 | INFO | LearningSynchronizer: | receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 9 -> 1]
```

```
node3 | 27m 52.586s | 2024-05-01 06:27:24.476 | WARN | AsyncOutputStream: | AsyncOutputStream interrupted
-- | -- | -- | -- | -- | --
node3 | 27m 52.587s | 2024-05-01 06:27:24.477 | ERROR | VirtualHasher: | Failed to wait for all hashing tasks
```

**Comment by anthony-swirldslabs** [comment]
Per http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20240501-053547-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/swirlds-logs.html , here's relevant logs before and during the failure:

```
node3	17m 57.025s	5/1/24 6:17:28.9	INFO	LearningSynchronizer:	learner calls receiveTree()
node3	18m 3.543s	5/1/24 6:17:35.4	INFO	LearningSynchronizer:	receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 7 -> 1]
node1	18m 5.479s	5/1/24 6:17:37.4	INFO	TeachingSynchronizer:	finished sending tree
node1	18m 5.486s	5/1/24 6:17:37.4	INFO	TeachingSynchronizer:	sending tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 8 -> 1]
node3	18m 5.538s	5/1/24 6:17:37.4	INFO	LearnerPushTask:	learner thread finished the learning loop for the current subtree
node3	18m 5.787s	5/1/24 6:17:37.7	INFO	LearningSynchronizer:	received tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 7 -> 1]
node3	18m 5.787s	5/1/24 6:17:37.7	INFO	LearningSynchronizer:	receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 8 -> 1]
node1	22m 31.539s	5/1/24 6:22:03.4	INFO	TeachingSynchronizer:	finished sending tree
node1	22m 31.728s	5/1/24 6:22:03.6	INFO	TeachingSynchronizer:	sending tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 9 -> 1]
node3	22m 31.957s	5/1/24 6:22:03.8	INFO	LearnerPushTask:	learner thread finished the learning loop for the current subtree
node1	27m 31.832s	5/1/24 6:27:03.7	ERROR	StandardWorkGroup:	Work Group Exception [ groupName = teaching-synchronizer ]
node3	27m 51.251s	5/1/24 6:27:23.1	INFO	LearningSynchronizer:	received tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 8 -> 1]
node3	27m 51.251s	5/1/24 6:27:23.1	INFO	LearningSynchronizer:	receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 9 -> 1]
node3	27m 52.587s	5/1/24 6:27:24.5	ERROR	VirtualHasher:	Failed to wait for all hashing tasks
```

**Comment by anthony-swirldslabs** [comment]
Normally, the `LearningSynchronizer:	received tree rooted at` comes right after the `LearnerPushTask:	learner thread finished`.

However, we see a gap after the entry at `node3	22m 31.957s	5/1/24 6:22:03.8` where the ``LearnerPushTask:	learner thread finished` is printed.

The corresponding `LearningSynchronizer:	received tree rooted at` comes 5 minutes later at `node3	27m 51.251s	5/1/24 6:27:23.1`

**Comment by anthony-swirldslabs** [comment]
The `VirtualHasher: 	Failed to wait for all hashing tasks` / `IllegalArgumentException: hash` exception is only printed at the 27 minutes mark, which means that it occurs after the reconnect timed out. So it seems that this exception is a result of the VirtualHasher trying to rehash a map that failed to reconnect completely, and so this seems to be a consequence rather than a cause of the reconnect failure.

**Comment by anthony-swirldslabs** [comment]
The fact that `learner thread finished the learning loop for the current subtree` gets printed at the 22 minutes mark suggests that the LearnerPushTask successfully completes its run() method with the `while (view.hasNextExpectedLesson()) {` loop w/o any exceptions, and that thread should then terminate.

However, the LearningSynchronizer seems to be still waiting on a call to `workGroup.waitForTermination();`, which subsequently returns and then it finally prints the `received tree rooted at` log for `0 -> 8 -> 1`, but this only happens at the 27 minutes mark. Note that again, no any exceptions, including InterruptedException, occur here.

So apparently, the `workGroup.waitForTermination();` is waiting for something other than the LearnerPushTask thread.

**Comment by anthony-swirldslabs** [comment]
The method does the following:

```
    public void waitForTermination() throws InterruptedException {
        futures.waitForCompletion();
        executorService.shutdown();

        while (!executorService.isTerminated()) {
            if (executorService.awaitTermination(10, TimeUnit.MILLISECONDS)) {
                break;
            }
        }
    }

```

**Comment by anthony-swirldslabs** [comment]
Note that the last `while (!isTerminated)` loop doesn't have a global timeout and would wait forever. So either the executorService takes 5 minutes to shutdown, or the futures would only complete after 5 minutes for this method to proceed.

**Comment by anthony-swirldslabs** [comment]
The `LearnerPushTask` submits its own `run()` to the workgroup, and so it gets submitted to the executorService, and its Future is added to the `futures`.

Since the logs above suggest that the LearnerPushTask is able to complete its job w/o any exceptions, unless there's some odd bugs in the `Executors.newCachedThreadPool`, it should finish normally and its Future should complete as well, all at the 22 minutes mark.

The only two other entities using the workGroup are the `in` and `out` data streams.

**Comment by anthony-swirldslabs** [comment]
Note that we observe the following:

```
node3	27m 52.564s	2024-05-01 06:27:24.454	ERROR	StandardWorkGroup:	Work Group Exception [ groupName = learning-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID -7441057967105127907(0x98BC0D340D9BCA1D) (class com.swirlds.common.merkle.synchronization.task.Lesson)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.threading.futures.ConcurrentFuturePool.lambda$waitForCompletion$2(ConcurrentFuturePool.java:154) ~[swirlds-common-0.50.0.jar:?]
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
	at com.swirlds.common.threading.futures.ConcurrentFuturePool.waitForCompletion(ConcurrentFuturePool.java:147) ~[swirlds-common-0.50.0.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.waitForTermination(StandardWorkGroup.java:167) ~[swirlds-common-0.50.0.jar:?]
```

**Comment by anthony-swirldslabs** [comment]
In the end, the exception above is `Caused by: java.net.SocketException: Connection reset`.

This specifically points to the `StandardWorkGroup.waitForTermination` waiting on a future associated with a thread from which a `Lesson` is being deserialized unsuccessfully. So it seems to be the `in` stream that keeps waiting for bytes that never come.

**Comment by anthony-swirldslabs** [comment]
And yes, the 5 minutes difference between the 22 and 27 minutes marks seem to come from:

`@ConfigProperty(defaultValue = "300s") Duration asyncStreamTimeout`

which is used as a `pollTimeout` in the `AsyncInputStream`.

**Comment by anthony-swirldslabs** [comment]
From reading the `AsyncInputStream` code, it seems that there's a non-zero `anticipatedMessages` counter value which causes its `run()` method to enter the message reading code, and that's where it eventually times out with the connection reset.

Since the `LearnerPushTask` previously reported that it finished receiving the current tree, it seems that it may be incrementing the `anticipatedMessages` counter more than needed.

**Comment by anthony-swirldslabs** [comment]
I'm not sure how the above can happen though, because each existing call to `in.anticipateMessage()` that increments the counter is always preceded by a call to `view.expectLessonFor()` which populates queues. And the `LearnerPushTask` would keep running for as long as there are items in those queues. But we've learned above that the `LearnerPushTask` finishes just fine w/o any exceptions at the 22 minutes mark.

**Comment by anthony-swirldslabs** [comment]
The only idea that I have is that this effect may be caused by an integer overflow/underflow behavior when the counter is incremented and decremented.

Note that the queues holding the expected lessons are implemented using sharded BitSet queues. This is done on purpose to support more than 2G items in those queues. However, the counter of the anticipated messages in the AsyncInputStream is an AtomicInteger. While the overflow/underflow logic in Java which wraps MAX_VALUE into the MIN_VALUE and vice versa can theoretically only cause the counter to become zero if we anticipate 4G messages, and hence the input stream would stop reading bytes, but in this particular case we observe a behavior where it actually keeps reading bytes while it shouldn't, so it's unclear how exactly this effect can be achieved. However, the fact that the queues support >2G and even >4G items by design but this counter does not support more than 2G items seems like a red flag.

**Comment by anthony-swirldslabs** [comment]
While we haven't reproduced the issue after the switch from AtomicInteger to AtomicLong was implemented above, I'm adding more debugging logs in case we encounter the failure again: https://github.com/hashgraph/hedera-services/pull/13755

**Comment by anthony-swirldslabs** [comment]
The above PR is merged and we now generate logs to monitor the process of finishing a learner task, as well as a start/finish/failure of the AsyncInputStream. Once the test fails in a similar fashion, the new logs should help us understand if a part of the finishing of the learner task gets stuck somewhere, as well as which specific input stream produces an exception.

Until we get these newer logs, no further progress can be made on this story.
