### ISSUE TITLE
HTS-Restart-AccountBalances-1k-26m  failure in AccountBalancesValidator

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1353]
**Summary of the defect**
HTS-Restart-AccountBalances-1k-26m  failure in AccountBalancesValidator as follows

```
First account balances file wasn't scheduled to be exported at epoch export boundary.
exportPeriod is 600 seconds. The file's export time is: 2021-05-03T07:01:00.077Z. First file name: 2021-05-03T07_01_00.077806Z_Balances.pb
```

**How to reproduce (if possible)**
Slack link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1620026125196100
Slack summary link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1620026168060000

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
This issue should be fixed by this PR: https://github.com/swirlds/swirlds-platform-regression/pull/1013, which is merged 5/3. 
And the renamed test running link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1620199331241200
But I do notice it's not stable. Another run with client validator failure: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1620631295363800. 

I will use this issue number to fix the new issue. A PR should be ready later tonight or tomorrow morning.
