### ISSUE TITLE
Gradle Build: Analyze 'Failed to transform ...jar problem'

### ISSUE THREAD

**Issue by jjohannes** [hashgraph/hedera-services#13655]
Sometimes building fails on local developer machines where the `build` folders (caches?) are in a certain state. Find out how to reproduce and fix this.

```
Execution failed for task ':swirlds-logging:compileJava'.
> Could not resolve all files for configuration ':swirlds-logging:compileClasspath'.
   > Failed to transform swirlds-config-extensions-0.51.0.jar (project :swirlds-config-extensions) to match attributes {artifactType=jar, javaModule=true, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=21, org.gradle.libraryelements=jar, org.gradle.usage=java-api}.
      > Execution failed for ExtraJavaModuleInfoTransform: hedera-services/platform-sdk/swirlds-config-extensions/build/libs/swirlds-config-extensions-0.51.0.jar.
         > Not a module and no mapping defined: swirlds-config-extensions-0.51.0.jar
```

**Comment by jjohannes** [comment]
Doing `--rerun-tasks` seems to fix the problem.

**Comment by jjohannes** [comment]
There seems to be som kind of **in-memory-caching-issue**. I had the situation that none of the class files were packaged into the Jars. Even when I did `--rerun-tasks` and/or `clean`.

Only `./gradlew --stop` solved it.

**Comment by jjohannes** [comment]
Possibly related: https://github.com/gradle/gradle/issues/27372

**Comment by Vampire** [comment]
I'd say this happens if for some reason `swirlds-config-extensions-0.51.0.jar` is missing the module info class. Maybe it sometimes is an empty jar or something like that. I don't think this is related to #27372, or at least my premature-transform-check did not yell. But if I add `tasks.jar { exclude("module-info.class") }` or delete the module info class from the jar and use `-x :swirlds-config-extensions:jar`, the exact error from OP comes.

**Comment by jjohannes** [comment]
We did not see this error anymore with our current setup and the latest Gradle / latest _extra-java-module-info_ plugin.
Closing this issue for now.
