### ISSUE TITLE
Update ReconnectNodeCount interface to log the new metrics

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#13749]
The existing `ReconnectNodeCount` interface logs the old reconnect metrics. It needs to be updated to log the new metrics tracked in `ReconnectMapStats`. We want them in the logs as well as the metrics so that the information is available when running locally or in unit tests.

**Comment by anthony-swirldslabs** [comment]
There's two caveats with the original description of this issue:
1. An instance of the `ReconnectMapStats` should exist in order to collect the metrics, so that they could be logged. However, the code in hedera-service will not have an instance of this object until https://github.com/hashgraph/hedera-services/issues/13748 is implemented (which is a sibling of this ticket.)
2. In general, our plan is to replace the old `ReconnectNodeCount` with the new `ReconnectMapStats`. Further, currently it's unclear whether a single `ReconnectMapStats` object would have all the relevant metrics because, for example, we'll be emitting per-map metrics eventually. Even further, it may be necessary to emit different `ReconnectMapStats` metrics on both the learner and the teacher. All these complications may lead to a single `ReconnectNodeCount` instance not being able to hold a reference to a single `ReconnectMapStats` instance that contains all the necessary metrics because such an object may not even exists. So it may make sense to make the `ReconnectMapStats` itself log its own metrics, rather than invent a way to keep using the old `ReconnectNodeCount` class.

Given the above, it appears that this ticket is currently blocked on https://github.com/hashgraph/hedera-services/issues/13748 because ultimately we need to start with having an instance of the metrics collector first, and only then will we be able to figure out how and where from to log the metric values.
