### ISSUE TITLE
Add round number to old state message

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#13851]
When a signed state is being kept in memory for a long time, an error is logged. It would be useful for this message to include more information about the state like the round number.

The error message is logged from `DefaultSignedStateSentinel.java`. Data from the history record needs to be made accessible.

**Comment by mxtartaglia-sl** [comment]
If all is good, It seems that we should be logging the round number:

![Image](https://github.com/hashgraph/hedera-services/assets/152629744/1f57c4a6-c3a4-4eb1-96a1-e889442f379c)

as we are logging the history object, and the "toString" of that object includes the round.

Went through the error reports in JTR channel and found this log line in previous failed tests:
```
2024-06-21 14:03:08.390 243      ERROR EXCEPTION        <ForkJoinPool-2-worker-33> DefaultSignedStateSentinel: Old signed state detected. The most likely causes are either that the node has gotten stuck or that there has been a memory leak.
null
```
The last null indicates that the history object is itself null.

I could determine that we are setting a non-null history object when `state.stateHistoryEnabled` property is true (it is false by default):

![Image](https://github.com/hashgraph/hedera-services/assets/152629744/8fc0c375-004f-42b3-b3b1-c755535ac9ef)

Given that this seems an expected behaviour, is this ticket valid? should we not log when the history object is null? can we get the information from another source? or should we enable stateHistoryEnabled?

**Comment by poulok** [comment]
This ticket is not valid, since the round is printed if state history is enabled.
