### ISSUE TITLE
 list of potential response codes that an EVM transaction could have in receipt

### ISSUE THREAD

**Issue by simsonraj** [hashgraph/hedera-services#14207]
Is there a potential list of on-chain errors that could be returned by the “receipts”?
For example, 
we already know “Insufficient_tx_fee” can be returned by the receipt. Please let us know if any of these errors or more could be returned through receipt other than the contract revert.

**Comment by Nana-EC** [comment]
Result of this ticket should be an MD file under https://github.com/hashgraph/hedera-services/tree/develop/hedera-node/docs/design/services/smart-contract-service that community members can refer to.

Essentially we should explore the following sources and build the smart contract related response codes that an execution could hit
- https://github.com/hashgraph/hedera-protobufs/blob/main/services/response_code.proto
- https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java

**Comment by MrValioBg** [comment]
Specifically for this ticket, what do we refer to as "EVM transaction"? I guess a contractCall transaction to a smart contract, should fall into that category for sure. But do we also include for example a contractCreate transaction? Because there are additional response codes, that are possible for contractCreate?

The main additional statuses for the receipt that can result from a contractCall that ends up with revert/halt reason are [here](https://github.com/hashgraph/hedera-services/blob/774ed309600e4b4acd9e1ca72fcd87d354c8b9ff/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java#L142-L168)
and halts are handled [here](https://github.com/hashgraph/hedera-services/blob/774ed309600e4b4acd9e1ca72fcd87d354c8b9ff/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/failure/CustomExceptionalHaltReason.java#L60-L85). 

Before creating a specification I would like to clarify if we would also want to include statuses for contractCreate, as there are additional ones that are possible like ERROR_DECODING_BYTESTRING or CONTRACT_BYTECODE_EMPTY.

@simsonraj @Nana-EC

**Comment by Nana-EC** [comment]
@simsonraj please find the list of error code at https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/docs/design/services/smart-contract-service/evm-transaction-response-codes.md based on the resolution of this ticket
