### ISSUE TITLE
Create proposal for prehandle buffer

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#14594]
Event pre-handle signaling uses a countdown latch inside every event to synchronize pre-handle and handle. This is less than ideal for a number of reasons (will be stated in the proposal), so a different solution for this would be preferable.

**Comment by poulok** [comment]
@lpetrovic05 should we close this? The proposal seems stalled. I'm not even sure we need a guarantee that preHandle executes before handle. Or if it is, that should be something enforced by the application. The proposal can remain open, but since this is not a priority, I prefer to close this ticket.

**Comment by lpetrovic05** [comment]
> @lpetrovic05 should we close this? The proposal seems stalled. I'm not even sure we need a guarantee that preHandle executes before handle. Or if it is, that should be something enforced by the application. The proposal can remain open, but since this is not a priority, I prefer to close this ticket.

I don't know what the plan for prehandle is, I haven't heard back from Richard. I will close it
