### ISSUE TITLE
Create pre-validation step to `xlarge` runners usage

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#15418]
### Problem

The current `validation` job consists of multiple steps. One of the first steps is `download-state`. As the name suggests, this step is responsible for downloading the state and running simple preliminary validation to ensure that all critically important files are downloaded. If the validation fails (either because files are absent for one reason or another, or the set of files is incomplete), it retries the download. This job does that up to 45 times, which takes up to 25 minutes.

Now, consider a scenario in which the node is misconfigured or the validator configuration is outdated. In this case, there is no chance that the state files will be downloaded, meaning that 25 minutes of the `xlarge` runner will be wasted. Given the fact that the validation itself takes about 3-4 minutes, it's a huge amount of waste.

### Solution

Introduce a `pre-validation` job that has the same logic as `download-state` but runs on a `medium` runner. Even if the medium runner gets blocked on retries, the amount of wasted resources would be significantly smaller.

The main challenge of this task is to coordinate two matrices. The `validation` job runs for 30 nodes in parallel, and with the introduction of the `pre-validation` job, there should be parallel independent pipelines:
```
node0: pre-validation -> validation
node1: pre-validation -> validation
...
node30: pre-validation -> validation
```

If node0 gets stuck in retries during `pre-validation`, node1 should not be affected and should proceed to the `validation` job after the `pre-validation` job has successfully completed.

Additionally, the `download-state` step and alert jobs associated with it must be present in both jobs.

**Comment by thenswan** [comment]
I tried several possible solutions to address this problem:
- Coordinating two matrices: In this approach, I created a job similar to 'validate' called 'pre-validate'. The main difference is that the 'pre-validate' job doesn't include the 'Run validations' step, as its primary purpose is to check if the state can be downloaded for each given node. I also updated the 'needs' in 'validate' by adding 'pre-validate'. However, this approach did not succeed because the 'validate' job didn't run until each node in 'pre-validate' was completed. Thus, parallel pipelines were not achieved.
- Using `workflow_dispatch`: The main goal was to run the 'validation' job when the state was successfully downloaded for a given node in 'pre-validation'. Although it may be technically possible to achieve the goal using this method, it complicates the current setup since each validation would run as a completely new workflow. This would make the Actions tab very messy. Triggering jobs (not workflows), however, is not possible.
