### ISSUE TITLE
Update TransactionRecordService to efficiently summarize net transfers (ℏ or HTS units)

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1588]
**Summary**
The [fledgling `TransactionRecordService`](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/records/TransactionRecordService.java) is meant to efficiently (i.e., without reference to any gRPC types) accumulate the net transfers of ℏ and HTS units that occur in a transaction.

**Comment by ljianghedera** [comment]
This issue involves more parts than it appears and it will take more thinkings and planning to do it well. And it will be better to tackle after (or before) other custom fee related issues are done, not at the same time. Since those custom fee issues are of higher priority so I will close this for now and will revisit this issue later.
