### ISSUE TITLE
WRONG CHAIN_ID error when executing pre-EIP-1559 transactions.

### ISSUE THREAD

**Issue by se7enarianelabs** [hashgraph/hedera-services#15953]
### Description

When submitting a pre-EIP-1559 Ethereum transaction on the Hedera network, the `chain_id` is incorrectly converted. Specifically, an additional `0` is added at the beginning of the `chain_id`, causing a mismatch during the chain ID validation.

For example:
- Chain ID `11155111` is incorrectly converted to `00aa36a7` (with an extra leading `0`) for pre-EIP-1559 transactions.
- For post-EIP-1559 transactions, the same chain ID is correctly converted to `aa36a7`.

This issue causes the [matchesChainId](https://github.com/hashgraph/hedera-services/blob/43df250316934b7b129f022259eb293d2dc5e823/hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java#L342) method in Hedera to fail validation, leading to a `WRONG CHAIN_ID` error when executing pre-EIP-1559 transactions.

Example pre-EIP-1559 Ethereum transaction:  
[Sepolia Etherscan Example](https://sepolia.etherscan.io/tx/0x1009199f804a4c75d266627548dc154989eec8385c7b3a67e2bd50a5db5063c9)
Example post-EIP-1559 Ethereum transaction:  
[Sepolia Etherscan Example](https://sepolia.etherscan.io/tx/0x1009199f804a4c75d266627548dc154989eec8385c7b3a67e2bd50a5db5063c9)

When comparing the two chain IDs as byte arrays:
- Pre-EIP-1559: `[0, -86, 54, -89]`
- Post-EIP-1559: `[-86, 54, -89]`

This causes the following validation in Hedera to return false:
```java
public boolean matchesChainId(final byte[] hederaChainId) {
    return chainId == null || chainId.length == 0 || Arrays.compare(chainId, hederaChainId) == 0;
}
```

### Steps to reproduce

1. Submit a pre-EIP-1559 Ethereum transaction on the Hedera network.
2. Attempt to execute the transaction.
3. The matchesChainId method will fail to validate the chain ID, resulting in a WRONG CHAIN_ID error.

### Hedera network

mainnet, testnet, previewnet, other

### Version

v0.1.0

### Operating system

None

**Comment by arianejasuwienas** [comment]
**Cause of the error:**

When using a CHAIN_ID represented as a BigInteger, an additional byte is required to store the sign information (indicating whether the value is positive or negative), if there is no free bit available for this information, as in values like 11155111.

As a result, the previous code caused BigInteger.toByteArray to return a value with an unexpected extra byte, leading to validation failures and other issues. For example, the message payload contained this extra byte, which caused attempts to derive the signer from the message and signature to return an incorrect signer ID instead of the correct one.
