### ISSUE TITLE
On notification of first successful state save after restart, perform any cleanup of  *-config.txt files. 

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#16419]
**Background**

The following behavior should only happen if `AddressBook.useRosterLifecycle` is `true`.

`genesis-config.txt` is processed exactly once at genesis start because it is ignored when there is a state on disk to load. 

`config.txt` is processed exactly once when there is no roster state content in the merkle state.

`override-config.txt` will get processed every restart unless we add some way of preventing it from being re-processed.   

The following solution is sufficient for now, but will be updated in a future proposal.  

Once the `override-config.txt` is processed and turned into the next active roster, write an empty file called `override-config.txt-<roundnumber>` to the directory where the `<roundnumber>` is the state's round number.  In future restarts, if this empty file is present and the state's round number matches, then apply the network override.   If the state's round number does not match, then do not apply the network override.  This will apply the network override to the same state, but not future or past states.   

**Acceptance Criteria** 

* Manual verification
* Create a test for startup where the override is not applied due to presence of the marker file. 

**Dependencies** 

The roster lifecycle flag must be implemented.  https://github.com/hashgraph/hedera-services/issues/16351

Positive test scenarios coincide with https://github.com/hashgraph/hedera-services/issues/16357

**Comment by poulok** [comment]
`genesis-config.txt` - this never HAS to be moved because if there is a state on disk, this file will be ignored. Sure, maybe it’s nice to clean it up at some point, but not essential.

`config.txt` - this is only used when there is an upgrade, so if a node crashes and restarts, it will be ignored. Not essential to clean it up, and probably should not be cleaned up since we don’t do that today.

`override-config.txt` - now this one has the potential to cause an ISS on a crash and restart once we implement DAB phase 3. However, the plan is for this file to only ever be used for a state transplant process which will not happen on production networks. Sure, it is good to clean up it up so that if a node crashes and restarts in a migration test, it doesn’t ISS. But it’s not critical for it to be atomic. Now, if we ever find a use for the override-config in production, it become important to have the atomic cleanup. But I think this can be completed later. Another option here to avoid the need for atomicity is to have the services startup code append the round number of the state loaded from disk to the override-config.txt, if it doesn't already have it. That way, if the node crashes and restarts after a new state is written to disk, it can check the round number. If it is lower that the round of the latest state on disk, it knows to just move the file to the archive directory and not make changes to state. If it is equal to the round number, it knows to apply it.

**Comment by mhess-swl** [comment]
Covered in PR #16594
