### ISSUE TITLE
ci: review and remove useInMemoryPgpKeys function from gradle

### ISSUE THREAD

**Issue by andrewb1269hg** [hashgraph/hedera-services#16548]
In a file path similar to this: `gradle/plugins/src/main/kotlin/com.hedera.gradle.maven-publish.gradle.kts`

We need to verify there is not a section such as:
```
useInMemoryPgpKeys(
  providers.environmentVariable("SIGNING_KEY").get(),
  providers.environmentVariable("SIGNING_PASSPHRASE").get()
)
```

We pass the GPG Keys though to the pipeline as secrets, so we should only use GPG signing and remove the section above, if it exists.

**Comment by jjohannes** [comment]
I was thinking (from experience in other projects) that `useInMemoryPgpKeys` might be the simpler overall mechanism. That's why we introduce it in https://github.com/hashgraph/hedera-cryptography when we did the initial setup.

Looks like this was the wrong call.

You already removed it from **hedera-cryptography** 

It is now removed from **hiero-gradle-conventions** as well (https://github.com/hiero-ledger/hiero-gradle-conventions/pull/16)

There are no more occurrences in https://github.com/hashgraph and https://github.com/hiero-ledger.
