### ISSUE TITLE
GenesisNetworkInfo should use AddressBook, not Roster.

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#16643]
**Background**

The current code reads config.txt on genesis, constructs a genesis address book, then constructs a genesis roster from the AB, and finally constructs the GenesisNetworkInfo from the genesis roster. 

https://github.com/hashgraph/hedera-services/blob/acbc5b6db856ed005a0406f1476420e49bba423e/hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java#L607-L613

What should happen is that the roster is not created until just before handing the roster over to the platform.   The `GenesisNetworkInfo` should be constructed using the genesis AddressBook.  

In the `node.proto` in translating from `AddressBook`, the order of gossip endpoints should be internal ip address at index 0 and external ip address at index 1.   

**Acceptance Criteria**

Rosters are not created until we're ready to give it to the platform. 

When constructing a roster, the order of gossip endpoints is reversed.  external at index 0 and internal at index 1.  

**Notes**

**Comment by mhess-swl** [comment]
Closing this ticket as no longer required. As part of the ongoing roster and TSS work, services needs the app to load a new series of network JSON files (specifically for restart tests) instead of `config.txt`, thereby making this interim step obsolete. Essentially the code becomes:
```java
        if (trigger == GENESIS) {
            final var config = configProvider.getConfiguration();
            final var ledgerConfig = config.getConfigData(LedgerConfig.class);
            genesisNetworkInfo = new GenesisNetworkInfo(requireNonNull(genesisNetwork), ledgerConfig.id());
        }
```

This change is now included in PR #16843. 
CC @edward-swirldslabs (just confirming what was discussed in #16759)
