### ISSUE TITLE
Design of Block Stream Bucket Uploader

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#16770]
Please write a short design doc covering the Bucket Uploader's essential design. 

As a minimum, it should contain:

- A description of how the uploader can be configured.
- A section that explains the flow of events in the happy case, if an error occurs, and in the case of a duplicate block.

**Comment by derektriley** [comment]
https://github.com/hashgraph/hedera-services/blob/16770-block-stream-bucket-uploader-design/hedera-node/docs/proposals/block-stream-bucket-uploader.md

**Comment by derektriley** [comment]
The block retention manager should be doing the deletion of files on another thread, if it's triggered from HandleWorkflow we shouldn't block the main thread, will update design doc.

**Comment by thomas-swirlds-labs** [comment]
Nice! The lightweight libraries are under consideration but I suspect that MinIO SDK may emerge as the leading candidate so you might be able to use that to inform the design and update some of the code samples 

![Image](https://github.com/user-attachments/assets/b3509bd1-ba4d-4f61-851d-e244f7044e59)

**Comment by derektriley** [comment]
We will need to consider a mechanism for when the block fails to upload to not be deleted after the expiration time. For example we may need to write a metadata file to disk to indicate if that block uploaded successfully. Otherwise the current design just has a retention manager which deletes files after a configurable amount of time but is unaware if the upload succeeded. This is sort of an edge case.

**Comment by derektriley** [comment]
Need to determine if a more secure way for bucket credentials should be used.

**Comment by derektriley** [comment]
Will move this design artifact to a Notion page. Closing this issue.
