### ISSUE TITLE
Investigate failure in timingSensitive tests

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-services#16806]
The extended test suite is failing to complete successfully due to errors in the timingSensitive test group. The error is shown [here](https://github.com/hashgraph/hedera-services/actions/runs/12036462273/job/33557791869)

```text
> Task :PlatformTestingTool:timingSensitive
  com.swirlds.demo.merkle.map.MapValueFCQTests ✘ initializationError

    java.lang.NullPointerException: Cannot invoke "com.swirlds.platform.crypto.SerializableX509Certificate.getCertificate()" because "this.sigCert" is null
        at com.swirlds.demo.merkle.map.MapValueFCQTests.setUp(MapValueFCQTests.java:84)
```

Talking with @Neeharika-Sompalli it looks like it might be an access issue where `test/resources` is not able to be accessed from `testFixtures`.

This has been breaking on the develop branch for most of the last week and is preventing CITR build promotion.

**Comment by jjohannes** [comment]
> Talking with @Neeharika-Sompalli it looks like it might be an access issue where test/resources is not able to be accessed from testFixtures.

Yes that is by design.

- `src/test` is for (unit) tests of a module, nothing can access this from the outside
- `src/testFixtures` is for fixtures potentially shared with other projects

 If resources are part of the test fixtures, they need to be put into `testFixtures/resources`.
If the test fixture code is correct as it is, please move the corresponding files there – `agrCerts.data` and `sigCerts.data`.

When I do this, the test is failing with another issue:

```
Invalid class ID 253095242501945279(0x3832CC837AB77BF) at index 2 for parent with class com.swirlds.demo.platform.PlatformTestingToolState
com.swirlds.common.merkle.exceptions.IllegalChildTypeException: Invalid class ID 253095242501945279(0x3832CC837AB77BF) at index 2 for parent with class com.swirlds.demo.platform.PlatformTestingToolState
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.throwIfInvalidChild(AbstractMerkleInternal.java:157)
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.setChild(AbstractMerkleInternal.java:100)
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.setChild(AbstractMerkleInternal.java:96)
```

IMO, as there is no general setup problem, but the individual test setup is wrong, this should be owned by the team responsible for the test (not DevOps).

**Comment by Neeharika-Sompalli** [comment]
@lpetrovic05  created this issue https://github.com/hashgraph/hedera-services/issues/16829 and investigating it from platform side.

**Comment by lpetrovic05** [comment]
@imalygin has fixed it with this PR https://github.com/hashgraph/hedera-services/pull/16864

**Comment by jjohannes** [comment]
Thank you @imalygin and @lpetrovic05.
