### ISSUE TITLE
Ensure `switch` and `if...else if` constructs always have a default branch

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#2094]
### Problem

When extending e.g. an `enum`, it is possible to overlook implications for an existing`switch` or `if/else if` that has no default branch.

Applicable to:
- hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java (lines 91 and 103)
- hapi-fees/src/main/java/com/hedera/services/usage/token/TokenBurnUsage.java (line 55) 
- hapi-fees/src/main/java/com/hedera/services/usage/token/TokenMintUsage.java (line 63) 
- hapi-fees/src/main/java/com/hedera/services/usage/token/TokenWipeUsage.java (line 55) 
- hedera-node/src/main/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMarshal.java (line 145)

### Solution

Ensure all such `switch` and `if...else if` constructs have a default branch.

**Comment by felipeneuhauss** [comment]
I'll work on it.

**Comment by volodymyrtaras-intellecteu** [comment]
@tinker-michaelj according to my recent view, the issue is not present anymore

hapi-fees/src/main/java/com/hedera/services/usage/token/TokenBurnUsage.java - class does not exist
hapi-fees/src/main/java/com/hedera/services/usage/token/TokenMintUsage.java - class does not exist
hapi-fees/src/main/java/com/hedera/services/usage/token/TokenWipeUsage.java - class does not exist

hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java - all else-if/switch statements have default branch
hedera-node/src/main/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMarshal.java - all else-if/switch statements have default branch

so this issue can be closed
