### ISSUE TITLE
PrefetchProcessor is broken

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#2546]
### Description

`PrefetchProcessor` creates `ThreadPoolExecutor` with a preconfigured number of core threads. However, the default policy of the executor is to start core threads when new tasks are submitted. `PrefetchProcessor` doesn't submit tasks via `execute/submit` so the pool is never populated, tasks pushed directly to the queue are never executed, the queue quickly gets full and an endless flow of warnings "Pre-fetch queue is FULL!" are logged.

### Steps to reproduce

Reproducible in development environment with `ContractCallLoadTest`.

### Hedera network

other

### Version

v0.20.0

### Operating system

Linux

**Comment by superboo** [comment]
I realized the prefetch logic wasn't working properly a while ago.

https://github.com/hashgraph/hedera-services/issues/2427

Unfortunately, the PR didn't merge correctly due to conflicts with the base layer (was originally built on top of smart-contracts/virtual-map branch). After the release was bumped out, the PR didn't get reworked.

I've currently rebased the original fix on top of vm-plus-020-test.3. We can either close this issue as a duplicate or just keep it and close both later.

**Comment by tinker-michaelj** [comment]
Fixed in VM branch.
