### ISSUE TITLE
Enable developers to run Local node

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#2893]
Enable to create a local node , so that smart contract developers can deploy the data to the nodes and run tests. As a first step, enable Local node using https://github.com/hashgraph/hedera-network-e2e

- Use `gcr.io/hedera-registry/uploader-mirror` for uploaders
- Use `gcr.io/hedera-registry/main-network-node` for network-node
- Use `gcr.io/mirrornode/` for mirror node containers

- [x] Update to use latest version of services and mirror node images

**Mirror node containers**  
 - [x] MinIO for uploader with bucket `hedera-streams`
- [x]  REST API for query
- [x]  Postgres DB 
- [x] importer to import onjects from s3 bucket `hedera-streams`
 - [x]  GRPC
 

 **Consensus nodes containers**
 - [x] network node
 - [x] network node postgres
 - [x] S3 bucket to store record streams/event streams/ account balances/stats in MinIO server
- [x] Use a single `docker-compose.yml` to run services and mirror node instead of two seperate docker-compose files 
2. Second Stage : Use JRS for creating local network for the developers at Hedera

**Comment by Neeharika-Sompalli** [comment]
WIP at https://github.com/hashgraph/hedera-network-e2e/compare/test-local-node

**Comment by 3Nigma** [comment]
Instead of a resource-intensive `minio`, you could also upgrade the mirror-node code to bypass the S3 API and consume records from a docker mounted volume.

[We forked the mirror-node code and have experimented with this a while ago](https://github.com/buidler-labs/hedera-mirror-node/pull/1) but have since stopped at the writing tests phase. 

If you think it's worth it, we can prioritize it to have a PR available.

**Comment by Neeharika-Sompalli** [comment]
@3Nigma That seems reasonable. But, merging this PR might delay initial LocalNode toolkit release. We will reconsider this change in near future once the initial release is completed. Thanks
