### ISSUE TITLE
Add support for EIP-3540: EVM Object Format (EOF) v1

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#3804]
### Problem

Our current EVM model does not utilize the upcoming Shanghai details of [EIP-3540: EVM Object Format (EOF) v1](https://eips.ethereum.org/EIPS/eip-3540)

### Solution

Add support for EIP-3540: EVM Object Format (EOF) v1

- [ ] Fill out details of solution
- [ ] Add a design doc if it's not a simple fix
- [ ] Link an implementing PR

**Comment by shemnon** [comment]
Main implementation will be in the hyperledger Besu repository - https://github.com/hyperledger/besu

An early draft is implemented in this branch - https://github.com/shemnon/besu/tree/EOF

Because the tree is basically locked down for the merge, this Code will land in Besu no sooner than November 2022, and furthermore is subject to change until the Shanghai Fork is locked in.  Could be Q1 2023, could be Q3.

Impact to hedera-services code should be fairly transparent.  Expected impact on services code is (a) a library upgrade and (b) a line or two to configure some options.  Given the slippery nature of when Ethereum forms actually activate we may want to activate it via a dynamic property, however we will want to test it in integration and perf prior to shipping.  We don't want to ship it into hedera's testnet prior to it activating in an Ethereum Mainnet test network, as EIPs have changed as soon as a week before such testnets.

**Comment by Nana-EC** [comment]
SHould be done but let's confirm

**Comment by lukelee-sl** [comment]
Fixed with this pr in the Besu repo https://github.com/hyperledger/besu/pull/4644
