### ISSUE TITLE
Add HIP 513 traceability state file to regular migration tests

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#3872]
### Problem

The regular services migration tests utilize state files to help ensure load and other items in migration tests.
These currently do not contain a state that ensure an optimal number of contracts with state changes and actions are included prior to migration

### Solution

Add a state file  to regular migration tests that support traceability tests, may contain

- **850 > `numContracts` < 1000,** 
- **90 000** < `**numKVPairs**` **< 100 000**

**Comment by Kalina-Todorova** [comment]
As per conversation about this, extracting a state file is not applicable:
- This test may take a while to execute and also it will generate a lot of data on disk (mainly in sidecar files for bytecode and state changes)
- Since the migration is a one-time event, it won't be necessary post release
- We have good coverage on the migration logic in other unit tests
