### ISSUE TITLE
create2 fails on non-zero wei

### ISSUE THREAD

**Issue by Shungy** [hashgraph/hedera-services#4357]
### Description

`create2(v, p, n, s)` returns zero (i.e.: failure) when `v` is `callvalue()` and that call value is non-zero.

My assumption is that it fails due to transfer tax causing insufficient wei to be transferred. If that is the case, I expect all of the below assembly calls to return zero when `v` is non-zero:

* `create(v, p, n)`
* `create2(v, p, n, s)`
* `call(g, a, v, in, insize, out, outsize)`
* `callcode(g, a, v, in, insize, out, outsize)`

Please consider testing all of the above cases.

### Steps to reproduce

1. Create a contract named `PayableCreate`.
2. Have a payable function like below:

```solidity
function testPayableCreate() external payable {
    bytes memory bytecode = type(PayableCreate).creationCode;
    assembly {
        if iszero(create2(callvalue(), add(bytecode, 0x20), mload(bytecode), caller())) {
            revert(0,0)
        }
    }
}
```

3. Call the function with non-zero payable amount and watch the call revert.
4. Optional: Replace `callvalue()` with `0` and it will work.

### Hedera network

testnet

### Version

n/a

**Comment by stoqnkpL** [comment]
Hi @Shungy !

I'm sorry for not getting back to you sooner.

I was able to execute a `create2` with a non-zero value by calling a contract with the `testPayableCreate()` function you provided successfully. I opened https://github.com/hashgraph/hedera-services/pull/4642 to illustrate this with an end-to-end test.

Please keep in mind that since you're using the `caller()` as `_salt`, only one create2 deployment will be allowed for each external address that's calling the function. Every subsequent call will try to redeploy at the already existing contract address. So if you first call the function without value and then you call the function a second time with value with the same caller address, it is normal to fail.

Please let me know if there's anything else I can help with, otherwise, I'll close this issue as resolved.

**Comment by Shungy** [comment]
Interesting. I will try to find the actual issue I had. It was definitely not a same salt issue.
