### ISSUE TITLE
Does expiration of contracts with fungible and non fungible (both with and without royalties) show up properly in records?

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4843]
- [x] #4846

**Comment by lbaird** [comment]
This is good. And the autorenew should have this behavior:

1. If a contract reaches the expiration date, and doesn’t have enough to
renew for the minimum period (3 months), it “expires” but isn’t deleted. It
is in a grace period.

2. During the grace period, if the background thread reaches it, and it has
enough hbars to pay for the whole grace period plus 3 months, then
autorenew. Otherwise, do nothing.

3. After the grace period, the first time the background thread reaches it,
it will try to autorenew. If it has enough to pay for the grace period plus
a little more (less than 3 months), then go ahead and use the available
hbars to autorenew for as long as possible, bringing the HBAR balance to
zero. If it can renew for the grace period plus the full 3 months, then do
that. If it doesn’t have enough to pay for the entire grace period, then
charge for what it could pay (which will bring the balance to zero hbars),
and then delete the smart contract and its associated account.

**Comment by Neeharika-Sompalli** [comment]
Merged with https://github.com/hashgraph/hedera-services/pull/4888
