### ISSUE TITLE
Disable all logging in CI

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4914]
We are having an issue seeing failures. Before we can do that we need to disable logging in CI.

**Comment by mhess-swl** [comment]
From @tinker-michaelj and @nathanklick:

> JUnit Platform Runner emits console output at runtime
the code in the @Test method may potentially emit console output via System.out.println() or log.X() methods
the code under test executed by the @Test method may also emit console output via System.out.println() or log.X() methods

> Items #2 and #3 are captured internally by the JUnit Platform runner and then re-emitted to both the console and written in the <test-suite-name>.xml JUnit XML report as a huge CDATA section

> Items #2 and #3 need to goto a log file and not emitted on the console which by virtue also includes them in the JUnit XML report as a CDATA blob

> Many of the XML parsers including libxml, libxml2, and the native java XML facilities impose maximum CDATA sizes

> the junit platform runner will write arbitrarily large CDATA blobs which many XML parsers will refuse to parse

>If items 2 & 3 goto a log, you will still see the JUnit Platform Runner output which includes tests executing, passing, failing along with any exceptions or assert failures emitted by the tests on the console output

**Comment by mhess-swl** [comment]
I removed all calls to `logIt(...), `.logged()`, and `.logging()` from the integration tests and got a clean upload of the test results:
<img width="1421" alt="without-logging_Screenshot 2023-02-13 at 14 12 11" src="https://user-images.githubusercontent.com/112430600/218594470-c4902852-97e8-40cc-a9fc-62503e126ecd.png">

Running _with_ the logging produces errors like the following, suggesting the issue is indeed a CDATA section that is too large:
<img width="1421" alt="Screenshot 2023-02-13 at 14 16 56" src="https://user-images.githubusercontent.com/112430600/218594707-1ee53f68-1258-4fac-b4a8-d61bef164d8c.png">

**Comment by mhess-swl** [comment]
I did the following steps in hopes of fixing the issue:
* Added a new `log4j2.xml` file to the `test-clients` directory, which suppresses any logs below ERROR level
* Reverted the commit that removed the `logging()`, `logIt(...)`, and `logged()` calls
* Re-ran with CI to see if the result is now parseable (since the XML CDATA is now much smaller).

The CI run failed as expected (see [here](https://github.com/hashgraph/hedera-services/actions/runs/4177123873/jobs/7234305069) for details) and the CDATA size is tiny, but unfortunately we're still not able to see _why_ the test failed :(

Test successfully fails:
<img width="647" alt="Screenshot 2023-02-14 at 12 25 42" src="https://user-images.githubusercontent.com/112430600/218841745-3bb35528-a422-48e6-b603-4168e05ba7b2.png">

`TEST-*.xml` files totals < 1 MB as hoped, but there is now no output to show what went wrong in the test:
<img width="1826" alt="Screenshot 2023-02-14 at 12 26 01" src="https://user-images.githubusercontent.com/112430600/218841868-a8f23030-1735-4e46-b2ce-c3db48aff576.png">

**Comment by mhess-swl** [comment]
Running the same test locally, I do get error text in the test XML file as expected, so it's not a question of whether this test outputs any errors:
<img width="1401" alt="Screenshot 2023-02-14 at 13 06 25" src="https://user-images.githubusercontent.com/112430600/218851010-a07bf834-d861-41f6-b229-9fd8ba8d1c9b.png">

**Comment by mhess-swl** [comment]
I'm also looking at how much space is taken up by the PBJ `TEST-xxx.xml` files on my local machine to see if the enormous amount of PBJ-generated _unit_ tests has any impact on the unit test task (or any other task) reporting in CI. Here are the results from my machine:

<img width="1623" alt="Screenshot 2023-02-15 at 16 33 55" src="https://user-images.githubusercontent.com/112430600/219221307-1f087877-01df-4ee4-ba08-d637453aafa6.png">

**Comment by mhess-swl** [comment]
After running the build in CI, I was surprised to see that the PBJ-generated tests weren't run at all for this run (presumably because none of the PBJ objects changed):

<img width="850" alt="Screenshot 2023-02-15 at 17 43 09" src="https://user-images.githubusercontent.com/112430600/219230236-369768f2-1619-4f9c-b8e2-3f1bfa5f4fd0.png">

I was also surprised to see that no logging was displayed for the unit tests despite ~16 MB of output from the unit tests alone:

<img width="1809" alt="Screenshot 2023-02-15 at 17 27 35" src="https://user-images.githubusercontent.com/112430600/219230813-a7e1e5ff-3a09-45fe-b485-40731a1813de.png">

There weren't any visible CDATA parsing errors, so I would expect to see some logging output somewhere. Not sure why CI isn't showing any of it.

**Comment by mhess-swl** [comment]
Running unit tests locally, it doesn't look like there's a need to put the modified log4j config in the `hapi` and `hedera-mono-service` modules because the `hapi` tests don't run very often and because the output for unit tests is typically small anyway. We can revisit if we need to, but for now I don't see any reason to reconfigure the logging.
