### ISSUE TITLE
Proposal: Event Prehandle Rearchitecture

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#5583]
### Background

Current state:
![eventflow-threads](https://user-images.githubusercontent.com/102969658/224412992-a92e6868-c4f0-4296-b0ec-2c658ede05ce.jpg)

- System and app prehandling is done in different ways
    - System transaction prehandle is performed on a dedicated thread (red in the diagram above)
    - App prehandle is performed on the intake thread (blue in the diagram above). This puts unnecessary load on (and adds uncertainty to) the intake thread

### Proposal
- Modify `PreConsensusEventHandler` so that the method for pre handling is configurable
- Rather than having a single `PreConsensusEventHandler` instance, create a separate instance for system transaction and for app transaction handling
    - The `EventObserverDispatcher` can pass all events into each `PreConsensusEventHandler`, in series
    - Each `PreConsensusEventHandler` instance will have its own queue with a handling thread
- Rather than passing events for app prehandle through the `TransactionHandler` object, just call `SwirldState::preHandle` directly from `SwirldStateManagerImpl`
    - The existing `TransactionHandler` isn't adding any value
    - Notice, the `TransactionHandler` is still in use in the chart below for *consensus* handling. I believe it can be entirely removed at some point, but this proposal is scoped such that consensus handling remains untouched  
- Rename the pre-consensus handle methods in `SwirldStateManagerImpl` to remove ambiguity
    - `handlePreConsensusEvent` -> `preHandleSystem` (or maybe `preHandlePlatform`?)
    - `preHandle` -> `preHandleApp` 
- Rename the method in `PreConsensusEventObserver` to something more informative, like `observe` (optional)

Full proposal diagram: 
![eventflow-threads](https://user-images.githubusercontent.com/102969658/224412698-22de69c3-55e2-4e03-b853-0cf680f405b9.jpg)

**Comment by poulok** [comment]
> Modify PreConsensusEventHandler so that the method for pre handling is configurable

We definitely should do this. The only reason it went to `SwirldStateManager` was the SS1 use case which has been removed.

> Rather than having a single PreConsensusEventHandler instance, create a separate instance for system transaction and for app transaction handling

I'm don't see the benefit here since application transactions do not get handled pre-consensus anymore.

> Rather than passing events for app prehandle through the TransactionHandler object, just call SwirldState::preHandle directly from SwirldStateManagerImpl

This makes sense now that we are only supporting SS2. Although leaving it separate does consolidate all application transaction handling in a single class, and it is very easy to test.

> Rename the pre-consensus handle methods in SwirldStateManagerImpl to remove ambiguity
>   -handlePreConsensusEvent -> preHandleSystem (or maybe preHandlePlatform?)
>   -preHandle -> preHandleApp

Be careful with terms here. preHandle is not the same as preConsensus handle. Or, at least it wasn't when we had the SS1 use case. It is still true that these events are being handle pre-consensus, and it is at a different point in the system than the pre-handle call.

I am out of time thinking about this proposal and need to put more time into it. I think there was a reason preHandle is done on the eventIntake thread, though i can't remember if it was a good reason. I know that it used to be the `expandSignatures()` method where the application could attach more signatures to the transaction and it was important this happened before the transaction was handled post-consensus. More to discuss here.

**Comment by alittley** [comment]
> preHandle is not the same as preConsensus handle
When we discuss more let's go over this - in my mind I've viewed these concepts as equivalent, so I need to find where my misunderstanding lies.

> application transactions do not get handled pre-consensus anymore
I'm assuming this has something to do with preHandle vs preConsensusHandle? Another point I need to get straight

> Although leaving it separate does consolidate all application transaction handling in a single class, and it is very easy to test.
IMO having this consolidated isn't particularly helpful, and the existing tests are minimal (1 brief test). In any case, this suggestion is a minor note, and would be fine either way.

**Comment by poulok** [comment]
Now that SS1 has been removed, they are equivalent except for the guarantee that `preHandle` is called on every event BEFORE it reaches consensus. There is no such guarantee with `preConsensusHandle` despite the name. Whether or not it is important to maintain this guarantee should be discussed. I don't know the answer off hand.

**Comment by alittley** [comment]
An additional topics for discussion:

Is the `preHandle` guarantee that events are handled before reaching consensus something that services currently rely on? Or was this something necessary for SS1? If that guarantee was made for SS1, can it be walked back?
