### ISSUE TITLE
Update PBJ DataIO to support all platform-data serialization requirements

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#5588]

**Comment by artemananiev** [comment]
Assuming we want to get rid of raw `ByteBuffer` usages in Platform Data code and replace it with `Bytes` or `BufferedData` (or `RandomAccessData`), the following capability is missing: random write access. `RandomAccessData` today defines a number of method to read at a given offset, but no methods to write. `ByteBuffer` we use today has such methods, e.g. `putInt(int offset, int value)`

**Comment by artemananiev** [comment]
A few more observations:

* ByteBuffer's methods like `clear()` can be easily chained, as they return the buffer. Similar methods in BufferedData (`reset()`) return void
* Some names are confusing. I understand the idea behind using `readInt()` vs `getInt()`, as the library supports both streams and buffers. However, names like `readBytes()` and `writeBytes()` are confusing. Semantics of these methods is confusing, too. `BufferedData.readBytes()` corresponds to `ByteBuffer.put()`, and `BufferedData.writeBytes()` is similar to `ByteBuffer.get()` Not very intuitive
* When a `BufferedData` object wraps an existing byte buffer, all buffer state (like position or limit) must be changed only using `BufferedData` APIs, not using the wrapped buffer directly, otherwise it will be a mess. This is currently not possible, at least because of lack of writing methods above

In general, I currently don't quite get the idea behind PBJ data I/O library, at least from Platform Data perspective. It provides an extra layer of abstraction (=> performance overhead) with no clear benefits. @jasperpotts ?

**Comment by artemananiev** [comment]
I don't think something needs to be done here. Random write API is covered in a separate ticket. Existing PBJ APIs are enough for MerkleDb to use protobuf as serialization format as proven in MerkleDb PBJ branch (#5592, just merged into develop).
