### ISSUE TITLE
Review hedera-app for problems following merge from develop

### ISSUE THREAD

**Issue by kimbor** [hashgraph/hedera-services#5828]

**Comment by jsync-swirlds** [comment]
In reviewing hedera-app, I encountered several tests that are completely commented out.  I don't have the depth of context to fix those, but I suspect they need to be fixed before we complete the merge.
The commented out tests:
* MerkleHederaStateTest
* MerkleSchemaRegistryTest
* ResponsibleVMapUser.release (just one method in this case; not sure if it's needed, but it does release resources used in testing...)
* SerializationTest
* StateLifecyclesTest
* MonoThrottleAccumulatorTest
* AdaptedMonoTransitionRunnerTest
* HandleWorkflowModuleTest
* IngestCheckerTest
* A few test methods in QueryCheckerTest remain commented out
* QueryDispatcherTest
I also have a couple minor fixes on a branch `05828-review-hedera-app` that aren't critical.
I've reviewed the rest of the files in hedera-app, and found no clear errors from the develop merge.

**Comment by mhess-swl** [comment]
I’ve gone through all the remaining tests in hedera-app. I’ve fixed many of the compiler errors on the `hedera-app-part4` branch, but there are a couple errors it’s not immediately obvious what the new values should be:
* SerializationTest: seems ok to cast `HederaState` as `MerkleHederaState` here, yes?
* StateLifecyclesTest: Not sure if `registerServiceSchemasForMigration(...)` is supposed to translate to separate `registerService(...)` calls or something else...?
`ResponsibleVMapUser.release(…)`: I have no clue what to do with this

There are also some test failures in the following classes:
* MerkleHederaStateTest – fixed all but one. Wasn’t sure, should the `MerkleHederaState.migrate(...)` method call onInit? (It doesn’t right now, which is why the test fails)
* SerializationTest – getting `No class with id=811144504921768448(0xB41C3A12D5F4200) found` on this one
StateLifecyclesTest – Fixed
IngestCheckerTest – @netopyr fixed [here](https://github.com/hashgraph/hedera-services/pull/5892)

I’ll keep working on these, but if anyone has more familiarity (especially on the state-related issues) then it’d be helpful to get more eyes on it.

**Comment by mhess-swl** [comment]
I believe everything is fixed now except for `SerializationTest`. @tinker-michaelj is looking at the issue(s). Then we'll run spotless and mark the PR as ready to review

**Comment by kimbor** [comment]
Last test was fixed. Closing as completed.
