### ISSUE TITLE
move SpecialFiles stores to FileService, rename to UpgradeFiles

### ISSUE THREAD

**Issue by kimbor** [hashgraph/hedera-services#6234]
Dependent on #6178

**Comment by jsync-swirlds** [comment]
I don't think UpgradeFiles belongs in FileService, as it's a one-off that is different from absolutely every other file, and is only ever used in the Network-Admin service.  It probably belongs in the one service that uses it.  We can adjust the way it's tracked in state to make sense for that move, rather than trying to shoehorn that special one-off case into a structure that it doesn't match.
