### ISSUE TITLE
Evaluate usage of InstantSource in platform

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#7163]
In the services team, we decided to use `java.time.InstantSource` instead of `com.swirlds.base.time.Time`. I think it would make sense to use `InstantSource` in the platform, too. (Sorry, I was unaware of this interface when I introduced `Time` in the platform repository.)

**Comment by hendrikebbers** [comment]
@cody-littley any problem withs such a refactoring?

**Comment by hendrikebbers** [comment]
If we do that we need the same functionality as we currently have in `Time` (including the test support)

**Comment by mxtartaglia-sl** [comment]
## Context
Assuming that we want to reduce complexity by changing our ad-hoc time abstraction for another provided by the language API, Let's consider the current situation:

Interface `Time`, is defined as:
```
public interface Time {

    long nanoTime();

    long currentTimeMillis();

    @NonNull
    Instant now();

    @NonNull
    static Time getCurrent() {
        return OSTime.getInstance();
    }
```
Its default implementation is `OSTime`, implementing the interface as follows: 
```
    public long nanoTime() {
        return System.nanoTime();
    }

    public long currentTimeMillis() {
        return System.currentTimeMillis();
    }

    public Instant now() {
        return Instant.now();
    }
```
The following notes in each javadoc:
_System.nanoTime:_ is an `@IntrinsicCandidate`; Returns the current value of the running Java Virtual Machine's high-resolution time source, in nanoseconds. This method can only be used to measure elapsed time and is not related to any other notion of system or wall-clock time. The value returned represents nanoseconds since some fixed but arbitrary origin time (perhaps in the future, so values may be negative). 

_System.currentTimeMillis_: is an `@IntrinsicCandidate`; Returns: the difference, measured in milliseconds, between the current time and midnight, January 1, 1970 UTC.

Both are very fast methods with very low granularity.

With some other ignored factory methods, `InstantSource` interface is defined as follows: 
```
public interface InstantSource {

   static InstantSource system() {
        return SystemInstantSource.INSTANCE;
    }
    
   Instant instant();

   default long millis() {
        return instant().toEpochMilli();
    }
}
```

**Considerations:**

- We could replace `Time#now` for `InstantSource#instant` and `Time#currentTimeMillis` for `InstantSource#millis`
- Although they are equivalent values, `instant().toEpochMilli()` is slower than `System.currentTimeMillis()`
- There is no method in `InstantSource` that, out of the box, provides elapsed time in nanoseconds.

## Possible solutions
### Approach 1: Completely remove Time and subclasses and replace its use with `InstantSource`
To achieve this, we should be ok with introducing the time penalty for the millisecond resolution. After that, to solve the nanosecond value, we could compute as follows:
```
Instant now = source.instant();
return now.toEpochMilli() * 1_000_000 + now.nanoTime();
```
**Considerations:**

- This would calculate nanoseconds since epoch and change functionality since `System.nanoTime() `(underlying implementation of `Time#nano`) is not tied to the system clock. In contrast, `toEpochMilli()` reflects the current time according to the system clock.
- Accuracy and granularity: Precision lost, according to our own `NanoClock` class: The standard Java "Instant" clock is only accurate to the nearest millisecond. NanoClock was created to overcome this issue.

###  Approach 2: Change abstractions, use NanoClock
`NanoClock` extends `Clock` and is an `InstantSource`, too. But still, it does not expose the possibility of querying for the system nanosecond time. 
We can extend the class to expose that information.
But we would still need to create our interface that exposes the `#nanos()` method and a device to create the right instance, given that we will no longer be able to use `InstantSource.system()` with this approach. 

**Considerations:**

-  Performance: Given that NanoClock needs to perform an arithmetic operation each time to keep a precise and accurate nanosecond count,` NanoClock#instant()` is slightly slower than an `InstantSource#instant()` but more granular and precise.
- This approach doesn’t seem to simplify our code and to successfully remove all our custom abstractions.
  
### Approach 3: Interface segregation 
While `Time#now` and `Time#getCurrent` can be replaced by `InstantSource#system` and `InstantSource#instant()` , `Time#millis` and `Time#nanoTime` could belong to a different abstraction level called TimeSource(?). 
With this, we could replace all uses of the first two methods with the existing Java API and leave the latter two for our custom implementation that, similar to OSTime, would still be fast.

**Considerations:**

- The impact on the codebase is substantial, requiring modifications in places where both instant instances and nanosecond time are utilized.
- It introduces a potential source of confusion, given the introduced complexity of having the two concepts separated, especially considering that InstantSource already provides a mechanism (although slow) for getting millisecond values


From the search in the codebase, these are the places where we should introduce those modifications whenever these instances are created.
```
TaskSchedulerMetricsBuilder.java 
	StandardFractionalTimer
		IntegerEpochTime: uses TimeSource concept
		RateLimitedLogger
			RateLimiter uses InstantSource concept
```
```
ShadowGraphSynchronizer.java 
	method createSendList uses InstantSource concept and TimeSource concept
```
```
EventCreationManagerFactory.java 
	method  buildEventCreationManager method needs an InstantSource for  
		TipsetEventCreator and EventCreationRule and a TimeSource for EventCreationManager
```
```
ChatterCore.java 
	method recordProcessingTime and newPeerInstance (OtherEventDelay)
 needs an InstanceSource and TimeSoruce for ProcessingTimeSendReceive, HeartbeatSendReceive
```

## Conclusions
In these three scenarios, replacing our ad-hoc code with existing Java API is only possible by carefully considering various trade-offs, including a possible performance impact, the exchange of existing complexities for new ones, and the impact on the codebase.

**Comment by mxtartaglia-sl** [comment]
Closing this pull request after discussion with @poulok @hendrikebbers @cody-littley @netopyr . We agreed that the gain from this pr is minor in comparison with the scope of the change.
