### ISSUE TITLE
Connectivity issue to Hedera Mainnet

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-services#755]
RST_STREAM errors on every connection attempt from developer. Connection attempted with each Mainnet Node.

- Network admin confirmed ports are open.
- IP address was shared with Hedera and whitelisted.
- Connection works if the developer uses his mobile phone as a hotspot

**Comment by nathanklick** [comment]
@donaldthibeau @gregscullard Do we have any additional information regarding their IP address ranges and network infrastructure? 

If he can access the network using a mobile hotspot, then it appears based on the information provided that it is a configuration issue on his corporate network. 

Here are some random WAG's as to what is happening:

- Corporate Firewall has HTTP & TLS deep inspection/intercept enabled and is not configured for or capable of parsing HTTP/2 payloads. 
- Corporate Firewall has HTTP & TLS deep inspection/intercept enabled and is denying the traffic. 
- Corporate Firewall has HTTP & TLS deep inspection/intercept enabled and our proxies are denying the traffic flow because they see it as a MITM attack. 
- Corporate Firewall does have HTTP inspection enabled and client is using plain-text transport. Corporate Firewall is interrupting traffic flow due to a policy or inspection rule violation. 
- Corporate Firewall does have HTTP/1.1 inspection enabled but HTTP/2 inspection is disabled or the firewall is incapable of HTTP/2 inspection.

**Comment by jsindy** [comment]
@nathanklick would an option be for them be to test with our SSL enabled port 50212?

**Comment by nathanklick** [comment]
@jsindy If they have not already tested using TLS, then it would definitely be worth a try to further isolate the issue.

**Comment by gregscullard** [comment]
@nathanklick @jsindy developer reports ports aren't blocked by firewall and connection doesn't work over 50212 either.

**Comment by jsindy** [comment]
Does their firewalls do deep packet inspection and can they view the firewall logs to determine if it could be blocked that way?

**Comment by iron4548** [comment]
I'm having this issue too (RST_STREAM errors). Tired using Client.forMainnet(), Client.forTestnet() and custom networks. 

I'm behind a corporate firewall as well.

I plan to create a IS helpdesk ticket, but need information to forward to them about what to try and help me isolate the problem. Any suggestion?

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
