### ISSUE TITLE
MerkleDB DataFileCommon Merge Bug

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#8034]
This failure was observed in the test `VMerkleDb-Basic-2.5k-110m`.

http://35.247.76.217:8095/swirlds-automation/develop/4N/VMerkleLong/20230816-053642-GCP-Daily-VMerkleLong-4N/VMerkleDb-Basic-2.5k-110m/

```
2023-08-16 07:47:28.629 4112     ERROR EXCEPTION        <<merkledb: Merging #0>> DataFileCommon: accounts_internalhashes has references to files [-2] that don't exists in the index. Latest new files = [8]
2023-08-16 07:52:46.135 7659     ERROR EXCEPTION        <<merkledb: Merging #0>> DataFileCommon: accounts_internalhashes has references to files [-2] that don't exists in the index. Latest new files = [8, 16]
2023-08-16 07:57:57.586 11139    ERROR EXCEPTION        <<merkledb: Merging #0>> DataFileCommon: accounts_internalhashes has references to files [-2] that don't exists in the index. Latest new files = [8, 16, 24]
```

**Comment by cody-littley** [comment]
Another manifestation of a similar looking problem was observed in http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20230816-053632-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/node0000/

**Comment by imalygin** [comment]
It looks like this issue is relatively harmless, and the bug is in the validation data link validation, not in the compaction itself. 

`com.swirlds.merkledb.files.DataFileCommon#printDataLinkValidation`:

```
        final ConcurrentMap<Integer, Long> missingFileCounts = LongStream.range(
                        validKeyRange.getMinValidKey(), validKeyRange.getMaxValidKey() + 1)
                .parallel()
                .map(key -> index.get(key, -1))
                .filter(location -> {
                    final int fileIndex = DataFileCommon.fileIndexFromDataLocation(location);
                    return !(validFileIds.contains(fileIndex)
                            || fileIndex > finalNewestFileIndex
                            || newFileIndexes.contains(fileIndex));
                })
                .boxed()
                .collect(Collectors.groupingByConcurrent(
                        DataFileCommon::fileIndexFromDataLocation, Collectors.counting()));
```
Here is how we're getting the missing files. Notice that the index of missing file is `-2` which is weird but can be explained by the following logic. This validation happens in a separate thread from the transaction thread. Therefore, concurrent modification of the index is possible. While we traverse `(minValidKey, maxValidKeyRange)` the index could have changed and some values could be no longer available and, therefore, ` index.get(key, -1))` returns `-1`. ` DataFileCommon.fileIndexFromDataLocation`, in its turn, is implemented so that it returns `-2`, if one passes `-1` there as an argument. Here is how we get `-2` as a file number which is not valid.

**Comment by cody-littley** [comment]
I have also observed this problem in 0.41, so when we fix we should back port the change. http://35.247.76.217:8095/swirlds-automation/release/0.41/4N/Reconnect/20230816-094136-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/
