### ISSUE TITLE
Platform status changed back to CHECKING from ACTIVE with no user transactions

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8188]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1692777116746189

Node's platform status change back to CHECKING from ACTIVE after restarting from upgrade

This is an intermittent issue

### Steps to reproduce

Run nightly regression panel `GCP-Daily-Update-CentOS7-4N-2C`

or `GCP-Daily-Update-4N-2C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by alittley** [comment]
Should be resolved with https://github.com/hashgraph/hedera-services/pull/8166

**Comment by alittley** [comment]
@JeffreyDallas I discussed with Cody, and we think the following is a *plausible* explanation of what happened:

- `node3`, which is observed briefly going into `ACTIVE` shortly after the upgrade, was missing some events from its PCES upon starting up.
- `node3` is the first node to reach the `OBSERVING` status, after having replayed what it did have from the PCES.
- When `node2` reaches the `OBSERVING` status, it syncs with `node3`, and sends some events from the PCES that `node3` was missing
- Some of these events were originally created by `node3`, so when `node3` sees a round coming to consensus, it observes self events reaching consensus, and therefore transitions to `ACTIVE`
- `node0` is the only node with non-zero weight in this test, and it isn't creating events yet at this point. Therefore, it isn't possible for consensus to advance, and `node3` eventually transitions back into `CHECKING`, since it doesn't see any more self events reach consensus
- Eventually, `node0` reaches `CHECKING`, and consensus can advance. At this time, `node3` again starts to see self-events reach consensus, and transitions to back to `ACTIVE`
_________________

Some observations, under the assumption that the above explanation is accurate:
- This behavior isn't a bug per-se, and wouldn't result in any bad behavior in a production environment
- This test failure will be fixed with https://github.com/hashgraph/hedera-services/pull/8136 , since PCES will be cleared at upgrade boundaries. 
- In the meantime, this behavior could be avoided by increasing the `platformStatus.observingStatusDelay` config value, such that all nodes reach the `OBSERVING` status and finish syncing prior to the first node reaching `CHECKING`

**Comment by JeffreyDallas** [comment]
What did you mean `node0 is the only node with non-zero weight ` ?

Since they all have non-zero stakes.

```
address, 0, node0000, node0000, 13875095657, 10.128.0.58, 30124, 146.148.68.57, 30124, 0.0.3
address, 1, node0001, node0001, 6887056580, 10.128.0.52, 30125, 34.135.57.90, 30125, 0.0.4
address, 2, node0002, node0002, 13656078660, 10.128.0.55, 30126, 34.72.192.142, 30126, 0.0.5
address, 3, node0003, node0003, 15581769103, 10.128.0.61, 30127, 34.16.0.152, 30127, 0.0.6
address, 4, fakeNode, fakeNode, 125, 100.142.0.40, 40127, 135.243.169.94, 40127, 0.0.100
nextNodeId, 5
```

**Comment by alittley** [comment]
@JeffreyDallas You need to look in the `data/saved/address_book` directory to see the actual address books that are used

[This](http://35.247.76.217:8095/swirlds-automation/develop/4N_2C/CentOS7_Update/20230823-063935-GCP-Daily-Update-CentOS7-4N-2C/Crypto-Update-Jar-1.5k-25m/node0000/data/saved/address_book/usedAddressBook_vServices%20%40%200.50.0%20%7C%20HAPI%20%40%200.40.0-blocks-state-SNAPSHOT_2023-08-23-07-15-51.txt) is the address book in use after the upgrade in this test

**Comment by alittley** [comment]
This should be fixed, since the merging of https://github.com/hashgraph/hedera-services/pull/8136

**Comment by alittley** [comment]
Expected fix is merged, and no new occurrences have been observed.
