### ISSUE TITLE
Investigate why weekend regression AWS instances are not shut down

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#841]
Every week after Saturday test , instances are not shut down, and needs to be shut down manually. This causes us to pay a lot of price without using the instances.
Investigate why they are not shutdown after weekend run .
![image](https://user-images.githubusercontent.com/52669918/101283293-06e60e00-379f-11eb-8eb5-482b185d1ccf.png)

Also, in us-west-2 region , none of the instances from Wednesday are shutdown.
https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1607264211120100

**Comment by JeffreyDallas** [comment]
We could figure out a way to launch self-terminating AWS instance.
Since all regression AWS instance is named something like "***-????m-***,
we could run a background script that will terminate itself after ???? minutes
 plus some buffer time, lets say extra 30 minutes
in case the developer need to ssh to do some debug.

https://stackoverflow.com/questions/10541363/self-terminating-aws-ec2-instance

**Comment by ljianghedera** [comment]
Should be fixed by PR: https://github.com/swirlds/swirlds-platform-regression/pull/715

**Comment by Neeharika-Sompalli** [comment]
Instances Launched on Dec11th and Dec12th did not get destroyed after the test. 
![image](https://user-images.githubusercontent.com/52669918/101990088-4e224200-3c6a-11eb-8b5b-1772afa725c5.png)

**Comment by ljianghedera** [comment]
Interesting. The root cause of this is the sync to s3 storage took more than 1 hour and get killed. 

[https://app.circleci.com/pipelines/github/hashgraph/hedera-services/7938/workflows/97973f88-82c0-4803-be9b-e63623528be1/jobs/45428](url)

**Comment by ljianghedera** [comment]
The root cause is tracked and solved by the platform issue : https://github.com/swirlds/swirlds-platform/issues/2799
