### ISSUE TITLE
Account with positive balance must be created via a cryptoCreate

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#859]
**Summary of the defect**
https://github.com/hashgraph/hedera-services/blob/1308f994ba95d4d76c004b319aafa33fa2fcac67/hedera-node/src/main/java/com/hedera/services/state/initialization/BackedSystemAccountsCreator.java#L81-L104

Only `GENESIS` account (also called `treasury` account) is created with `totalTinyBarFloat` during genesis.

**Comment by tinker-michaelj** [comment]
If you override the [`bootstrap.ledger.nodeAccounts.initialBalance` property](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/resources/bootstrap.properties#L8) to a non-zero value `N`, node accounts will be created with balance `N`; if you override the `bootstrap.ledger.systemAccounts.initialBalance` property to a non-zero value `M`, other system accounts will be created with balance `M`.

Then `0.0.2` gets all the remaining balance...is there another expected behavior?
