### ISSUE TITLE
Wiring framework follow up: funky flushing

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#9629]
Follow up with @edward-swirldslabs on his concerns over the wiring framework's flush implementation.

**Comment by edward-swirldslabs** [comment]
Given that the wiring framework has been in use for 2 months with parts of the system in the framework on mainnet, this issue is likely closeable as not being a valid concern.  Since I was the ultimate source of the issue, I'll take liberties and close it.  @cody-littley  you can re-open it if you feel like the conversation is still relevant.   I can't remember the details anymore.
