### ISSUE TITLE
Node never enters state FREEZE_COMPLETE

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#9827]
http://35.247.76.217:8095/swirlds-automation/develop/4N/ZeroStake/20231110-081924-GCP-Daily-ZeroStake-4N/FCM-Restart-Stake-2.5k-10m/

In the test `FCM-Restart-Stake-2.5k-10m`, I observed a failure because node 2 entered the state `FREEZING` but never managed to enter the state `FREEZE_COMPLETE`. This is odd to me, since the node did save the freeze state.

**Comment by alittley** [comment]
- The problem is that the freeze state saved while still in the 10s `OBSERVING` wait period, so there wasn't any trigger to push the platform out of `FREEZING` later on. 
- In practice, this race condition will only occur if a node were to be starting up at the very end of a freeze, or potentially if the node falls behind at exactly the wrong moment, right before a freeze.
- The effect of this bug is simply that the node would remain in `FREEZING`, instead of progressing to `FREEZE_COMPLETE`. The freeze state itself is still saved, but that goes unreported.

I propose the following solution:
In any platform status, if a freeze state is saved, transition immediately to `FREEZE_COMPLETE`. There is never anything to accomplish after a freeze state is saved, and adding this logic to every platform status ensures that no similar race conditions may arise in the future.
